# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://wallsync.net
title: WallSync
email: info@wallsync.net
author: Geoff Bullen
description: > # "WallSync - use your phone to keep in sync your physical wall and Agile tools such as JIRA. See live data as you look at your physical wall.  Augmented reality comes to Agile"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/startflowing
